init script has been enhanced : `nginx -t` called only once

diff --git a/debian/nginx-common.nginx.init b/debian/nginx-common.nginx.init
--- a/debian/nginx-common.nginx.init
+++ b/debian/nginx-common.nginx.init
@@ -39,11 +39,16 @@ if [ -n "$ULIMIT" ]; then
 fi
 
 test_nginx_config() {
-  if ! $DAEMON -t $DAEMON_OPTS >/dev/null 2>&1
+  set +e
+  OUTPUT=`$DAEMON -t $DAEMON_OPTS 2>&1`
+  retvar=$?
+  if [ $retvar -ne 0 ]
   then
-    $DAEMON -t $DAEMON_OPTS
-    exit $?
+    echo "Configuration test failed!" >&2
+    echo -n "$OUTPUT\n"
+    exit $retvar
   fi
+  set -e
 }
 
 start() {
